language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-command' ]; then cd .. && eval "mv $currentfolder generator-command" && cd generator-command; fi
